							<div class="zonegroup">
								<div id="L2_Zone70" class="EmptyPane pane w70">
								</div>
								<div id="L2_Zone30" class="EmptyPane pane w30">
								</div>
							</div>
<div class="zonegroup">
    <div id="L3_Zone50_1" class="EmptyPane pane w50">
    </div>
    <div id="L3_Zone50_2" class="EmptyPane pane w50">
    </div>
</div>
<div class="zonegroup">
    <div id="L4_Zone100" class="EmptyPane pane w100">
    </div>
</div>
<div class="zonegroup">
    <div id="L5_Zone40" class="EmptyPane pane w40">
    </div>
    <div id="L5_Zone60" class="EmptyPane pane w60">
    </div>
</div>
<div class="zonegroup">
    <div id="L6_Zone30" class="EmptyPane pane w30">
    </div>
    <div id="L6_Zone70" class="EmptyPane pane w70">
    </div>
</div>
<div class="zonegroup">
    <div id="L7_Zone30_1" class="EmptyPane pane w30">
    </div>
    <div id="L7_Zone40_2" class="EmptyPane pane w40">
    </div>
    <div id="L7_Zone30_3" class="EmptyPane pane w30">
    </div>
</div>
<div class="zonegroup">
    <div id="L8_Zone100" class="EmptyPane pane w100">
    </div>
</div>