<h4>Contest Scoreboard</h4>

<i>This shows the currently recognized points assigned for activities (shallow-forks, bugs filed, documentation artifacts) for the "Stick a fork in Windows" Contest.<br><br>
If something isn't showing up here, nudge @fearthecowboy with a <a href="http://twitter.com/home?status=Hey%2C+%40fearthecowboy%21+You+missed+my+...">tweet</a> or <a href="https://github.com/inbox/new/fearthecowboy">message</a></i>
<br></br>

<table width="100%" class="pretty-table" summary="Scoreboard for the Stick-a-fork-in-Windows contest">
    <caption>Current Results</caption>
    <tr>
        <th scope="col">Github ID</th>
        <th scope="col">Points</th>
        <th scope="col">References</th>
    </tr>
    <tr>
        <td scope="row">HamishC</td>
        <td>
        Forks: 0<br>
        Bugs: 0<br>
        Docs: 0</td>
        <td>
            <a href="https://github.com/coapp-packages/libpng">Forked libpng</a> <span class="smaller">(in review)</span><br>
            <a href="https://github.com/coapp-packages/libssh">Forked libssh</a> <span class="smaller">(in review)</span><br>
            <a href="https://github.com/coapp-packages/openssl">Forked openssl</a> <span class="smaller">(in review)</span><br>
            <a href="https://github.com/coapp-packages/sqlite">Forked SQLite</a> <span class="smaller">(in review)</span><br>
        </td>
    <tr>
    <tr>
        <td scope="row">ferzkopp</td>
        <td>Forks: 0<br>
        Bugs: 0<br>
        Docs: 0</td>
        <td>
            <a href="https://github.com/coapp-packages/libpng">Forked SDL </a> <span class="smaller">(in review)</span><br>
            <a href="https://github.com/coapp-packages/libssh">Forked SDK_gfx</a> <span class="smaller">(in review)</span><br>
        </td>
    <tr>
</table>

Items marked (in review) have not yet been evaluated for points, this should happen fairly soon...
