<h2>Contest Scoreboard</h2>

<table width="100%" class="pretty-table" summary="Scoreboard for the Stick-a-fork-in-Windows contest">
    <caption>Current Results</caption>
    <tr>
        <th scope="col">Github ID</th>
        <th scope="col">Points</th>
        <th scope="col">References</th>
    </tr>
    <tr>
        <td scope="row">HamishC</td>
        <td>
        Forks: 0<br>
        Bugs: 0<br>
        Docs: 0</td>
        <td>
            <a href="https://github.com/coapp-packages/libpng">Forked libpng (*)</a><br>
            <a href="https://github.com/coapp-packages/libssh">Forked libssh (*)</a><br>
            <a href="https://github.com/coapp-packages/openssl">Forked openssl (*)</a><br>
            <a href="https://github.com/coapp-packages/sqlite">Forked SQLite (*)</a><br>
        </td>
    <tr>
    <tr>
        <td scope="row">ferzkopp</td>
        <td>Forks: 0<br>
        Bugs: 0<br>
        Docs: 0</td>
        <td>
            <a href="https://github.com/coapp-packages/libpng">Forked SDL (*)</a><br>
            <a href="https://github.com/coapp-packages/libssh">Forked SDK_gfx(*)</a><br>
        </td>
    <tr>
</table>

Items marked (*) have not yet been evaluated for points
