<div id="FooterContentArea">
    <div class="zonegroup">
        <div id="L9_Zone25_1" class="EmptyPane pane w25">
        </div>
        <div id="L9_Zone25_2" class="EmptyPane pane w25">
        </div>
        <div id="L9_Zone25_3" class="EmptyPane pane w25">
        </div>
        <div id="L9_Zone25_4" class="EmptyPane pane w25">
        </div>
    </div>
</div>
<div id="Footer">
    <span id="Copyright"><span class="Copyright">Copyright &#169; 2011 CoApp Contributors</span></span> 
    <span id="Privacy"><a class="Terms" href="#" onclick="return false">Read about privacy</a></span> 
    <span id="Terms"><a class="Terms" href="#" onclick="return false">Read our terms</a></span> 
    <span id="disqus"><a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a></span>
</div>