<h4><u>Yet another new site!</u></h4>
<p>We were having issues with the CMS that we'd moved into, and it was going to be really problematic over the long run... So, we picked up and rebuilt again using <b><a href="https://github.com/mojombo/jekyll/wiki">Jekyll</a></b>, a rather ingenious little templating system that we can use for pretty much everything. <br>And, it's really fast!</p>
<p>I hope it's not giving you too many bumps... </p>
<!-- 
<div class="rightButton">
    <br>
    <a class="btn" href="#" onclick="return false">
    Read more</a> <br><br><br></div>
<p>Quisque volutpat mattis eros. Nullam malesuada 
erat ut turpis. Suspendisse urna nibh, viverra 
non, semper suscipit, posuere a, pede...</p>
-->    
<br><hr>