<div id="HeaderArea">
    <div id="Logo">
        <h1><a href="/" >
        <img alt="Logo" src="/images/logo3.png" style="border-width: 0px; position: absolute; left: 10px; top: 0px;">
        <span id="BigTitle">CoApp</span> <br>The Common Opensource 
        Application Publishing Platform </a></h1>
    </div>
    <div id="NavAux">
        <div id="Search">
            <div id="SearchContainer">
                <div id="SearchLink">
                    <img alt="Search icon" src="/images/search.icon.png"></div>
                <div id="SearchField" style="right: -300px;">
                    <div id="SearchBar">
                        <form action="" class="search-form" method="get">
                            <fieldset>
                            <input id="q" name="q" type="text" value=""><button type="submit">Search
                            </button></fieldset></form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear">
    </div>
</div>