<h4><u>CoApp at Oscon!</u></h4>
<p>Garrett Serack will be presenting a session at the O'Reilly Open Source Conference in Portland, OR on Wednesday, July 27.  Join him for his presentation <b><a href="http://www.oscon.com/oscon2011/public/schedule/detail/21158">CoApp - An Open Source Package Manager For Windows</a></b>, at 2:30 PM.</p>

<p>Post conference, you can view his presentation slides through the <b><a href="http://www.oscon.com/oscon2011/">OSCON Website</a></b>.</p>

<br><hr>